INSERT INTO country (id, name) VALUES (7, 'Австралия');
INSERT INTO country (id, name) VALUES (28, 'Беларусь');
INSERT INTO country (id, name) VALUES (21, 'Бельгия');
INSERT INTO country (id, name) VALUES (32, 'Бразилия');
INSERT INTO country (id, name) VALUES (3, 'Великобритания');
INSERT INTO country (id, name) VALUES (38, 'Венгрия');
INSERT INTO country (id, name) VALUES (10, 'Германия');
INSERT INTO country (id, name) VALUES (24, 'Германия (ФРГ)');
INSERT INTO country (id, name) VALUES (14, 'Гонконг');
INSERT INTO country (id, name) VALUES (22, 'Дания');
INSERT INTO country (id, name) VALUES (25, 'Индия');
INSERT INTO country (id, name) VALUES (39, 'Иордания');
INSERT INTO country (id, name) VALUES (19, 'Ирландия');
INSERT INTO country (id, name) VALUES (40, 'Исландия');
INSERT INTO country (id, name) VALUES (8, 'Испания');
INSERT INTO country (id, name) VALUES (17, 'Италия');
INSERT INTO country (id, name) VALUES (4, 'Канада');
INSERT INTO country (id, name) VALUES (37, 'Катар');
INSERT INTO country (id, name) VALUES (36, 'Кипр');
INSERT INTO country (id, name) VALUES (15, 'Китай');
INSERT INTO country (id, name) VALUES (23, 'Корея Южная');
INSERT INTO country (id, name) VALUES (35, 'Ливан');
INSERT INTO country (id, name) VALUES (20, 'Люксембург');
INSERT INTO country (id, name) VALUES (12, 'Мальта');
INSERT INTO country (id, name) VALUES (13, 'Марокко');
INSERT INTO country (id, name) VALUES (16, 'Мексика');
INSERT INTO country (id, name) VALUES (30, 'Нидерланды');
INSERT INTO country (id, name) VALUES (2, 'Новая Зеландия');
INSERT INTO country (id, name) VALUES (29, 'Норвегия');
INSERT INTO country (id, name) VALUES (26, 'ОАЭ');
INSERT INTO country (id, name) VALUES (18, 'Польша');
INSERT INTO country (id, name) VALUES (11, 'Россия');
INSERT INTO country (id, name) VALUES (5, 'СССР');
INSERT INTO country (id, name) VALUES (1, 'США');
INSERT INTO country (id, name) VALUES (31, 'Финляндия');
INSERT INTO country (id, name) VALUES (6, 'Франция');
INSERT INTO country (id, name) VALUES (34, 'Швейцария');
INSERT INTO country (id, name) VALUES (27, 'Швеция');
INSERT INTO country (id, name) VALUES (33, 'Югославия');
INSERT INTO country (id, name) VALUES (9, 'Япония');

INSERT INTO genre (id, name) VALUES (18, 'аниме');
INSERT INTO genre (id, name) VALUES (16, 'биография');
INSERT INTO genre (id, name) VALUES (17, 'боевик');
INSERT INTO genre (id, name) VALUES (20, 'вестерн');
INSERT INTO genre (id, name) VALUES (12, 'военный');
INSERT INTO genre (id, name) VALUES (3, 'детектив');
INSERT INTO genre (id, name) VALUES (1, 'драма');
INSERT INTO genre (id, name) VALUES (13, 'история');
INSERT INTO genre (id, name) VALUES (11, 'комедия');
INSERT INTO genre (id, name) VALUES (2, 'криминал');
INSERT INTO genre (id, name) VALUES (10, 'мелодрама');
INSERT INTO genre (id, name) VALUES (14, 'музыка');
INSERT INTO genre (id, name) VALUES (7, 'мультфильм');
INSERT INTO genre (id, name) VALUES (9, 'мюзикл');
INSERT INTO genre (id, name) VALUES (6, 'приключения');
INSERT INTO genre (id, name) VALUES (8, 'семейный');
INSERT INTO genre (id, name) VALUES (19, 'спорт');
INSERT INTO genre (id, name) VALUES (15, 'триллер');
INSERT INTO genre (id, name) VALUES (21, 'ужасы');
INSERT INTO genre (id, name) VALUES (4, 'фантастика');
INSERT INTO genre (id, name) VALUES (5, 'фэнтези');

# create user 'kpuser' identified by 'kpuser';
#
# grant all on kinopoiskdb.* to 'kpuser';